name: tests

on:
  push:
    branches:
      - "main"

permissions:
  contents: read

jobs:
  tests:
    name: tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2
      - uses: arduino/setup-task@v2.0.0
      - run: task test
